Upgrade to Webpack2 compatibility
coditorium/nodejs-swig-loader pull request #8
Opened 2017-03-15 11:33 UTC by CoenWarmer

Might not be the best implementation as I'm not super familiar with the Webpack Loader API, but it works and all tests pass :)

2017-03-15 11:35 UTC, CoenWarmer commented
Also, this is my first Github PR, so please be gentle ;)

2017-03-16 05:41 UTC, pmendelski requested changes
Congratulations for your first GitHub PR. Well done :)

There is just one change to be applied - extract function. When it's done I will merge your pr and release a new version.

BTW. It would be also nice if you could squash your commits into a single one. Though commit history of this repo is not perfect, so in this case it's not a big problem ;)

2017-03-16 05:41 UTC, mendlik commented on lib/swig-loader.js
> +	plugin.query = JSON.parse(JSON.stringify(queryString.parse(plugin.query, { arrayFormat: 'bracket' })));
Could you please extract `parseQuery` function.

Example:
```js
function parseQuery(query) {
  return JSON.parse(JSON.stringify(queryString.parse(query, { arrayFormat: 'bracket' })));
}
// ...
plugin.query = parseQuery(plugin.query);
plugin.resourceQuery = parseQuery(plugin.resourceQuery);
```

2017-03-16 05:42 UTC, CoenWarmer commented
Will do! Thanks :)

2017-03-16 09:55 UTC, CoenWarmer commented
Seems that by squashing commits I can't address your review comment through Github's UI anymore.. But it's in there! :)

2017-03-16 10:28 UTC, merged

2017-03-16 10:29 UTC, pmendelski commented
Thanks for your PR! :) When I get home I will publish it.

2017-03-16 21:37 UTC, mendlik commented
Published [swig-loader v2.0.0](https://www.npmjs.com/package/swig-loader)